[elasticsearch]
es-node-1 ansible_host=34.229.62.99
es-node-2 ansible_host=44.197.231.4
es-node-3 ansible_host=44.192.15.63

[elasticsearch:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/ec-node.pem
